/// Generate a Dart→TS interop fixture.
///
/// Unlike [`generate-fixture.mjs`] (TS→Dart), this fixture pins BOTH ephemeral
/// keypairs so the wire output is deterministic. noise-protocol@3 (used by the
/// TS side) doesn't support injecting IK ephemerals, but this Dart Noise
/// implementation does — so we can produce fully-deterministic handshake
/// messages and transport ciphertexts here, then have a TS test verify byte-
/// level decryption.
///
/// Why this matters: transport keys depend on both ephemerals via the `ee` and
/// `se` DH steps. If the Dart and TS halves disagree on ChaCha20-Poly1305
/// nonce encoding or on `Split()` output ordering, the TS side will fail to
/// decrypt this fixture's ciphertexts. That's the final nail in the interop
/// validation.
///
/// Run: `dart run tool/generate_interop_fixture.dart`
library;

import 'dart:convert';
import 'dart:io';

import 'package:shepaw/services/noise/noise_handshake_state.dart';
import 'package:shepaw/services/noise/noise_primitives.dart';
import 'package:shepaw/services/noise/noise_session.dart';

Future<void> main() async {
  // Long-term static keypairs.
  final initStatic = await noiseGenerateKeyPair();
  final respStatic = await noiseGenerateKeyPair();

  // Pinned ephemeral keypairs so the wire output is deterministic.
  final initEphemeral = await noiseGenerateKeyPair();
  final respEphemeral = await noiseGenerateKeyPair();

  const msg1PayloadText = '{"agentId":"acp_agent_dart","clientVersion":"shepaw/dart"}';
  const msg2PayloadText = '{"agentId":"acp_agent_dart","serverVersion":"acp-sdk/dart"}';
  const initToRespText = 'hello from dart initiator';
  const respToInitText = 'hello from dart responder';

  final init = await NoiseSession.initiator(
    staticPublicKey: initStatic.publicKey,
    staticPrivateKey: initStatic.privateKey,
    pinnedPeerStaticPublicKey: respStatic.publicKey,
    ephemeralForTesting: initEphemeral,
  );
  final resp = await NoiseSession.responder(
    staticPublicKey: respStatic.publicKey,
    staticPrivateKey: respStatic.privateKey,
    ephemeralForTesting: respEphemeral,
  );

  final msg1 = await init.writeHandshake1(utf8.encode(msg1PayloadText));
  final hs1 = await resp.readHandshake1(msg1);
  assert(utf8.decode(hs1.msg1Payload) == msg1PayloadText);
  final msg2 = await resp.writeHandshake2(utf8.encode(msg2PayloadText));
  final hs2 = await init.readHandshake2(msg2);
  assert(utf8.decode(hs2.msg2Payload) == msg2PayloadText);

  final initToRespCt = await init.encrypt(utf8.encode(initToRespText));
  final respToInitCt = await resp.encrypt(utf8.encode(respToInitText));

  // Sanity: both ciphertexts decrypt.
  assert(utf8.decode(await resp.decrypt(initToRespCt)) == initToRespText);
  assert(utf8.decode(await init.decrypt(respToInitCt)) == respToInitText);

  final fixture = {
    '_comment':
        'Dart→TS Noise IK interop fixture. Suite: Noise_IK_25519_ChaChaPoly_BLAKE2b. '
        'Generated by shepaw/tool/generate_interop_fixture.dart; consumed by the TS '
        'SDK cross-language test.',
    'suite': 'Noise_IK_25519_ChaChaPoly_BLAKE2b',
    'prologue_hex': _hex(noisePrologueDefault),
    'initiator': {
      'static_private_hex': _hex(initStatic.privateKey),
      'static_public_hex': _hex(initStatic.publicKey),
      'ephemeral_private_hex': _hex(initEphemeral.privateKey),
      'ephemeral_public_hex': _hex(initEphemeral.publicKey),
      'msg1_payload_utf8': msg1PayloadText,
      'msg1_hex': _hex(msg1),
    },
    'responder': {
      'static_private_hex': _hex(respStatic.privateKey),
      'static_public_hex': _hex(respStatic.publicKey),
      'ephemeral_private_hex': _hex(respEphemeral.privateKey),
      'ephemeral_public_hex': _hex(respEphemeral.publicKey),
      'msg2_payload_utf8': msg2PayloadText,
      'msg2_hex': _hex(msg2),
    },
    'transport': {
      'init_to_resp_plaintext_utf8': initToRespText,
      'init_to_resp_ciphertext_hex': _hex(initToRespCt),
      'resp_to_init_plaintext_utf8': respToInitText,
      'resp_to_init_ciphertext_hex': _hex(respToInitCt),
    },
  };

  // Write next to the agent-bridge interop dir AND into the Flutter test
  // fixtures so both halves of CI can consume it.
  const encoder = JsonEncoder.withIndent('  ');
  final out = encoder.convert(fixture);

  const outPath = 'test/fixtures/noise_interop_fixture_dart_to_ts.json';
  File(outPath).writeAsStringSync('$out\n');
  stderr.writeln('Wrote $outPath');
}

String _hex(List<int> bytes) {
  final sb = StringBuffer();
  for (final b in bytes) {
    sb.write(b.toRadixString(16).padLeft(2, '0'));
  }
  return sb.toString();
}
