import 'package:flutter/material.dart';
import '../../models/planning_models.dart';

/// A card widget displayed in the chat for users to approve or provide feedback
/// on an execution plan generated by the Admin agent.
class PlanApprovalCard extends StatefulWidget {
  final Map<String, dynamic> planData;
  final bool isResponded;
  final void Function(bool approved, {String? feedback, List<String>? skippedTaskIds}) onRespond;

  const PlanApprovalCard({
    super.key,
    required this.planData,
    required this.isResponded,
    required this.onRespond,
  });

  @override
  State<PlanApprovalCard> createState() => _PlanApprovalCardState();
}

class _PlanApprovalCardState extends State<PlanApprovalCard> {
  late ExecutionPlan _plan;
  bool _showFeedbackInput = false;
  final _feedbackController = TextEditingController();
  final Set<String> _skippedTaskIds = {};

  @override
  void initState() {
    super.initState();
    _plan = ExecutionPlan.fromJson(widget.planData);
  }

  @override
  void didUpdateWidget(PlanApprovalCard oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.planData != widget.planData) {
      _plan = ExecutionPlan.fromJson(widget.planData);
    }
  }

  @override
  void dispose() {
    _feedbackController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final responded = widget.isResponded;
    final approvedBool = widget.planData['_approved'] as bool?;

    return Container(
      margin: const EdgeInsets.symmetric(vertical: 4),
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHighest.withOpacity(0.5),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: responded
              ? (approvedBool == true ? Colors.green.shade300 : Colors.orange.shade300)
              : colorScheme.primary.withOpacity(0.4),
          width: 1.5,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
            decoration: BoxDecoration(
              color: colorScheme.primary.withOpacity(0.08),
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(11),
                topRight: Radius.circular(11),
              ),
            ),
            child: Row(
              children: [
                const Icon(Icons.assignment_outlined, size: 18),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    _plan.title.isNotEmpty ? _plan.title : '执行计划',
                    style: const TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 14,
                    ),
                  ),
                ),
                if (!responded)
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                    decoration: BoxDecoration(
                      color: Colors.orange.shade100,
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Text(
                      '等待确认',
                      style: TextStyle(
                        fontSize: 11,
                        color: Colors.orange.shade800,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  )
                else
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                    decoration: BoxDecoration(
                      color: approvedBool == true
                          ? Colors.green.shade100
                          : Colors.orange.shade100,
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Text(
                      approvedBool == true ? '已批准' : '已反馈',
                      style: TextStyle(
                        fontSize: 11,
                        color: approvedBool == true
                            ? Colors.green.shade800
                            : Colors.orange.shade800,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
              ],
            ),
          ),

          // Summary
          if (_plan.summary.isNotEmpty)
            Padding(
              padding: const EdgeInsets.fromLTRB(14, 10, 14, 4),
              child: Text(
                _plan.summary,
                style: TextStyle(
                  fontSize: 13,
                  color: Colors.grey[700],
                ),
              ),
            ),

          const Divider(height: 16, indent: 14, endIndent: 14),

          // Task list
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 14),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                for (int i = 0; i < _plan.tasks.length; i++)
                  _buildTaskRow(i, _plan.tasks[i], responded),
              ],
            ),
          ),

          const SizedBox(height: 8),

          // Buttons (only when not yet responded)
          if (!responded) ...[
            const Divider(height: 1, indent: 14, endIndent: 14),
            if (_showFeedbackInput) ...[
              Padding(
                padding: const EdgeInsets.fromLTRB(14, 10, 14, 4),
                child: TextField(
                  controller: _feedbackController,
                  maxLines: 3,
                  decoration: InputDecoration(
                    hintText: '请描述你对计划的修改意见...',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    isDense: true,
                    contentPadding: const EdgeInsets.all(10),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.fromLTRB(14, 4, 14, 10),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    TextButton(
                      onPressed: () => setState(() => _showFeedbackInput = false),
                      child: const Text('取消'),
                    ),
                    const SizedBox(width: 8),
                    FilledButton(
                      onPressed: () {
                        final fb = _feedbackController.text.trim();
                        widget.onRespond(
                          false,
                          feedback: fb.isNotEmpty ? fb : null,
                          skippedTaskIds: _skippedTaskIds.isNotEmpty
                              ? _skippedTaskIds.toList()
                              : null,
                        );
                      },
                      style: FilledButton.styleFrom(
                        backgroundColor: Colors.orange,
                      ),
                      child: const Text('提交意见'),
                    ),
                  ],
                ),
              ),
            ] else
              Padding(
                padding: const EdgeInsets.fromLTRB(14, 10, 14, 10),
                child: Row(
                  children: [
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () =>
                            setState(() => _showFeedbackInput = true),
                        icon: const Icon(Icons.edit_outlined, size: 16),
                        label: const Text('提出修改'),
                      ),
                    ),
                    const SizedBox(width: 10),
                    Expanded(
                      child: FilledButton.icon(
                        onPressed: () {
                          widget.onRespond(
                            true,
                            skippedTaskIds: _skippedTaskIds.isNotEmpty
                                ? _skippedTaskIds.toList()
                                : null,
                          );
                        },
                        icon: const Icon(Icons.check_circle_outline, size: 16),
                        label: const Text('批准并执行'),
                        style: FilledButton.styleFrom(
                          backgroundColor: Colors.green,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
          ] else
            const SizedBox(height: 6),
        ],
      ),
    );
  }

  Widget _buildTaskRow(int index, PlanTask task, bool responded) {
    final canSkip = !responded;
    final isSkipped = _skippedTaskIds.contains(task.id);

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '${index + 1}.',
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w600,
              color: Colors.grey[600],
            ),
          ),
          const SizedBox(width: 6),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: Text(
                        task.title,
                        style: TextStyle(
                          fontSize: 13,
                          fontWeight: FontWeight.w500,
                          decoration: isSkipped
                              ? TextDecoration.lineThrough
                              : null,
                          color: isSkipped ? Colors.grey : null,
                        ),
                      ),
                    ),
                    if (task.assignee.isNotEmpty)
                      Container(
                        margin: const EdgeInsets.only(left: 6),
                        padding: const EdgeInsets.symmetric(
                            horizontal: 6, vertical: 2),
                        decoration: BoxDecoration(
                          color: Colors.blue.shade50,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Text(
                          '@${task.assignee}',
                          style: TextStyle(
                            fontSize: 11,
                            color: Colors.blue.shade700,
                          ),
                        ),
                      ),
                  ],
                ),
                if (task.dependencies.isNotEmpty)
                  Padding(
                    padding: const EdgeInsets.only(top: 2),
                    child: Text(
                      '依赖: ${task.dependencies.join(', ')}',
                      style: TextStyle(
                        fontSize: 11,
                        color: Colors.grey[500],
                      ),
                    ),
                  ),
              ],
            ),
          ),
          if (canSkip)
            Checkbox(
              value: isSkipped,
              onChanged: (v) {
                setState(() {
                  if (v == true) {
                    _skippedTaskIds.add(task.id);
                  } else {
                    _skippedTaskIds.remove(task.id);
                  }
                });
              },
              materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
              visualDensity: VisualDensity.compact,
              side: BorderSide(color: Colors.grey.shade400),
              activeColor: Colors.orange,
            ),
        ],
      ),
    );
  }
}
